#!/usr/bin/env python3
import sys

sys.path += ['../src']

#from paperwork.paperwork import GtkMain
from paperwork.webend import main as WebEndMain

usage = "usage: paperwork [-w]\n"\
        "   -w: start local webserver on port 8001"

if __name__ == "__main__":
    print("Welcome!")

    if len(sys.argv) == 1:
        GtkMain()
    elif len(sys.argv) == 2:
        # check arguments
        if sys.argv[1] == "-w":
            WebEndMain()
        else:
            print(usage)
    else:
        print(usage)
